### ISSUE TITLE
error: expected constructor, destructor, or type conversion before ‘<’ token

### ISSUE THREAD

**Issue by dliessi** [LinusU/node-alias#2]
When building macos-alias from the Git repository with `node-gyp rebuild` I get the following error:

```
In file included from ../src/volume.cc:6:
../src/impl-apple.cc:28: error: expected constructor, destructor, or type conversion before ‘<’ token
make: *** [Release/obj.target/volume/src/volume.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 10.8.0
gyp ERR! command "node" "/opt/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/davide/Programmazione/node-alias
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
```

I'm on Mac OS 10.6.

**Comment by LinusU** [comment]
@dliessi 

Hi Davide,

I just updated this repository to Nan 2.0 but the code for Mac OS 10.6 doesn't work for me. Neither did it before I upgraded thought so I'm not sure if that is the problem.

It might be that the `FSGetCatalogInfo` is removed in OS X 10.10.

Are you still using 10.6? Would you be able to test if the latest version is working for you?

**Comment by dliessi** [comment]
@LinusU 
Hi.
Yes, I'm still on 10.6.
I actually had noticed that with recent versions of Node.js `node-alias` wasn't working for me, but I had no time at that moment to investigate further.
I've just tried the latest version of `node-alias` with Node.js 0.10.36 and it seems to build and work correctly.
Right now I'm upgrading Node.js to 0.12.7: I'll let you know the results of the test.

**Comment by dliessi** [comment]
With Node.js 0.12.7 and the latest version of `node-alias` I get the following:
```


  addon
dyld: lazy symbol binding failed: Symbol not found: _FSGetCatalogInfo
  Referenced from: /Users/davide/Programmazione/node-alias/build/Release/volume.node
  Expected in: flat namespace

dyld: Symbol not found: _FSGetCatalogInfo
  Referenced from: /Users/davide/Programmazione/node-alias/build/Release/volume.node
  Expected in: flat namespace

Trace/BPT trap
```

**Comment by LinusU** [comment]
Ah crap :(

That's the same error message that I'm getting. I have no idea why thought.

I'll open a new bug.
