### ISSUE TITLE
Library using an earlier version of nan

### ISSUE THREAD

**Issue by ducky427** [LinusU/node-alias#8]
Hi,
(Sorry to bother you again.)
This library can't be installed in io.js v3.x as it uses an older version of nan. 

This library is needed by `ds-store` which is used by `node-appdmg`.

Thanks a lot!

**Comment by LinusU** [comment]
It's actually `macos-alias`, I'll take a look now.

**Comment by ducky427** [comment]
ah yes. thanks a lot!!

**Comment by LinusU** [comment]
Sorry, actually you where absolutely right, I thought that this was reported on the appdmg repo. Sorry about that.

Still on it thought :rocket:

**Comment by LinusU** [comment]
Should be working now :+1:

**Comment by ducky427** [comment]
Thanks a lot! I'm now able to install node-appdmg because this installs fine. :+1:
